# Spring Boot JWT Authentication API Configuration
server:
  port: 8080

spring:
  # H2 Database configuration (in-memory for development)
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  # JPA/Hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop  # Creates tables on startup, drops on shutdown
    show-sql: true  # Show SQL queries in logs
    properties:
      hibernate:
        format_sql: true  # Format queries for better readability
    open-in-view: false  # Disable to avoid warning

  # H2 Console (for viewing database in browser)
  h2:
    console:
      enabled: true
      path: /h2-console

# JWT configuration
jwt:
  secret: ${JWT_SECRET:mySecretKeyForJwtTokenGenerationThatShouldBeLongEnoughForSecurity123456789}
  expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds

# Logging configuration
logging:
  level:
    com.davidfernandez.jwt_auth_api: DEBUG  # Detailed logs for your app
    org.springframework.security: INFO     # Spring Security logs